name       : tzdata
version    : 2021e
release    : 20
source     :
    - https://data.iana.org/time-zones/releases/tzdata2021e.tar.gz : 07ec42b737d0d3c6be9c337f8abb5f00554a0f9cc4fcf01a703d69403b6bb2b1
    - https://data.iana.org/time-zones/releases/tzcode2021e.tar.gz : 584666393a5424d13d27ec01183da17703273664742e049d4f62f62dab631775
license    : Public-Domain
component  : system.base
summary    : Timezone data files
description: |
    This package contains data files with rules for various timezones around the world.
setup      : |
    tar xf $sources/tzcode${version}.tar.gz
build      : |
    make tzdata.zi
install    : |
    tz="africa antarctica asia australasia backward etcetera europe factory northamerica southamerica"

    zic -y ./yearistype -d $installdir/usr/share/zoneinfo -L /dev/null $tz
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo/posix -L /dev/null $tz
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo/right -L leapseconds $tz
    # Default DST
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo -L /dev/null -p America/New_York $tz

    install -m00644 iso3166.tab zone.tab leapseconds tzdata.zi $installdir/usr/share/zoneinfo
