name       : tzdata
version    : 2022e
release    : 25
source     :
    - https://data.iana.org/time-zones/releases/tzdata2022e.tar.gz : 8de4c2686dce3d1aae9030719e6814931c216a2d5e891ec3d332e6f6516aeccd
    - https://data.iana.org/time-zones/releases/tzcode2022e.tar.gz : d40280253980e89168e6be4275a852bf9521524d47684de3135b9a5ca387710b
license    : Public-Domain
component  : system.base
summary    : Timezone data files
description: |
    This package contains data files with rules for various timezones around the world.
setup      : |
    tar xf $sources/tzcode${version}.tar.gz
build      : |
    make tzdata.zi
install    : |
    tz="africa antarctica asia australasia backward etcetera europe factory northamerica southamerica"

    zic -y ./yearistype -d $installdir/usr/share/zoneinfo -L /dev/null $tz
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo/posix -L /dev/null $tz
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo/right -L leapseconds $tz
    # Default DST
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo -L /dev/null -p America/New_York $tz

    install -m00644 iso3166.tab zone.tab leapseconds tzdata.zi $installdir/usr/share/zoneinfo
