name       : tzdata
version    : 2021c
release    : 18
source     :
    - https://data.iana.org/time-zones/releases/tzdata2021c.tar.gz : b4f1d1c8cb11c3500276dac862d8c7e6f88c69b1e8ee4c5e9d1daad17fbe3542
    - https://data.iana.org/time-zones/releases/tzcode2021c.tar.gz : a34eb356a317378a317057649dc4c7f7b2033052d720f10d91b1fd1d8c51da05
license    : Public-Domain
component  : system.base
summary    : Timezone data files
description: |
    This package contains data files with rules for various timezones around the world.
setup      : |
    tar xf $sources/tzcode${version}.tar.gz
build      : |
    make tzdata.zi
install    : |
    tz="africa antarctica asia australasia backward etcetera europe factory northamerica southamerica"

    zic -y ./yearistype -d $installdir/usr/share/zoneinfo -L /dev/null $tz
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo/posix -L /dev/null $tz
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo/right -L leapseconds $tz
    # Default DST
    zic -y ./yearistype -d $installdir/usr/share/zoneinfo -L /dev/null -p America/New_York $tz

    install -m00644 iso3166.tab zone.tab leapseconds tzdata.zi $installdir/usr/share/zoneinfo
